# Generated by Django 2.2.28 on 2024-12-27 12:01

import applications.news.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.TextField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=applications.news.models.upload_news_photo)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
    ]
