# Generated by Django 2.2.28 on 2024-12-27 12:01

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('award_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', ckeditor.fields.RichTextField()),
                ('by', models.CharField(max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
