# Generated by Django 2.2.28 on 2024-12-27 12:01

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='Publications')),
                ('tags', ckeditor.fields.RichTextField()),
                ('by', ckeditor.fields.RichTextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='files')),
                ('alt', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=255)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.Publication')),
            ],
        ),
    ]
