# Generated by Django 2.2.28 on 2024-12-27 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=20)),
                ('link', models.URLField(max_length=1000)),
                ('stipend', models.IntegerField(blank=True, null=True)),
                ('exp_req', models.IntegerField(blank=True, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, help_text='Brief Description of job profile', max_length=300, null=True)),
                ('posting_date', models.DateField()),
                ('location', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
