# Generated by Django 2.2.28 on 2024-12-27 12:01

import applications.alumniprofile.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degree', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('role', models.CharField(choices=[('S', 'Student'), ('A', 'Alumni')], default='A', max_length=2)),
                ('roll_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('year_of_admission', models.IntegerField(choices=[(2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')], null=True)),
                ('programme', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Des', 'B.Des'), ('M.Des', 'M.Des'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD')], max_length=1000)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ME', 'Mechanical Engineering'), ('SM', 'Smart Manufacturing'), ('NS', 'Natural Sciences'), ('MT', 'Mechatronics'), ('DS', 'Design'), ('NA', 'Not Applicable')], max_length=1000)),
                ('reg_no', models.BigIntegerField(default=0, editable=False, null=True)),
                ('name', models.CharField(default='', max_length=1000)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(max_length=254)),
                ('fathers_name', models.CharField(default='', max_length=1000)),
                ('spouse_name', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('mobile1', models.BigIntegerField(null=True)),
                ('mobile2', models.BigIntegerField(blank=True, null=True)),
                ('phone_no', models.BigIntegerField(blank=True, null=True)),
                ('current_address', models.TextField(default='', max_length=1000)),
                ('permanent_address', models.TextField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to=applications.alumniprofile.models.upload_photo)),
                ('working_status', models.CharField(blank=True, choices=[('Is Working', 'Is Working'), ('Is Pursuing Higher Studies', 'Is Pursuing Higher Studies'), ('Is Self Employed', 'Is Self Employed')], max_length=1000)),
                ('current_position', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_organisation', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_of_joining', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('past_experience', models.IntegerField(blank=True, null=True)),
                ('current_course', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_university', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkedin', models.URLField(blank=True, default='www.linkedin.com', null=True)),
                ('facebook', models.URLField(blank=True, default='www.facebook.com', null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('mail_sent', models.BooleanField(default=False)),
                ('verify', models.BooleanField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alumniprofile.Batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PastExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=1000)),
                ('emp_type', models.CharField(choices=[('ft', 'Full-time'), ('pt', 'Part-time'), ('se', 'Self-employed'), ('fr', 'Freelance'), ('in', 'Internship'), ('tr', 'Trainee')], max_length=10)),
                ('organisation', models.CharField(max_length=1000, verbose_name='Company/Org name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=200, verbose_name='Discipline/Field')),
                ('institute', models.CharField(max_length=1000, verbose_name='Institute Name')),
                ('admission_year', models.IntegerField(null=True)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumniprofile.Degree')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniprofile.Profile')),
            ],
        ),
    ]
