# Generated by Django 2.2.28 on 2024-12-27 12:01

import applications.events_news.models
import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', ckeditor.fields.RichTextField()),
                ('start_date', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 12, 0))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 12, 0))),
                ('by', models.CharField(max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=applications.events_news.models.upload_event_photo)),
                ('location', models.CharField(max_length=100, null=True)),
                ('address', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_news.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event_id', 'user_id')},
            },
        ),
    ]
